plugins: rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

# 例：新しく追加された Cop に対応
Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/RedundantCurrentDirectoryInPath:
  Enabled: true
